# SonarCloud configuration.
sonar.projectKey=forkbikash_wallet-transfer-assignment
sonar.projectName=wallet-transfer-assignment
sonar.organization=forkbikash
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/tests/**
sonar.exclusions=**/.git/**,**/.github/**,**/vendor/**,**/node_modules/**,**/coverage/**,**/bin/**,**/dist/**,**/*_test.go,**/tests/**
